name: Process .obj files and push .png output to 'Ausgabe' branch
on:
  push:
    branches: development-sodium
jobs:
  process_obj_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository main branch
        uses: actions/checkout@v4
        with:
          ref: development-sodium # Versuche den 'development-sodium' Branch zu laden, falls vorhanden
          path: sodium
          fetch-depth: 0 # Holt die gesamte Historie
      - name: Checkout repository ausgabe branch
        uses: actions/checkout@v4
        with:
          ref: dev/generate-vanilla # Versuche den 'dev/generate-vanilla' Branch zu laden, falls vorhanden
          path: vanilla
          fetch-depth: 0 # Holt die gesamte Historie
      - name: Clone additional repository 'objmc'
        run: |
          git clone https://github.com/EriolEandur/objmc.git objmc
          cd objmc
          git checkout master
          ls *
      - name: Get list of changed files
        id: changed_files
        run: |
          # Vergleicht den letzten Commit mit dem vorherigen und listet die geänderten Dateien auf
          #git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          #git diff-tree --no-commit-id --name-only -r ${{ github.sha }} > changed_files.txt
          #git diff --name-status ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          cd sodium
          git diff-tree --no-commit-id --name-status -r ${{ github.sha }} > ../changed_files.txt

      - name: Display changed files
        run: |
          ls *
          echo "The following files have changed:"
          cat changed_files.txt
      - name: Run Python script to generate vanilla RP files
        run: |
          sudo apt-get install python3-tk
          python3 -m venv venv
          source venv/bin/activate
          pip3 install pyyaml
          pip3 install Pillow
          python -c "from PIL import Image"
          python3 -c "from PIL import Image"
          python3 objmc/generate_vanilla.py
          ls vanilla/assets/minecraft/textures/block/apple_leaves*.png
          ls vanilla/assets/minecraft/models/block/apple_leaves*.json
      - name: set user
        run: |
          git config --global user.name "EriolEandur"
          git config --global user.email "erioleandur@users.noreply.github.com"
      - name: Add .png files to 'dev/generate-vanilla' branch and push
        run: |
          # Fügt die generierten .png- und .json-Dateien hinzu
          cd vanilla
          commit=0
          shopt -s globstar
          echo "png Files with globstar: "
          ls **/*.png
          if ls **/*.png 1> /dev/null 2>&1; then
            git add **/*.png
            commit=1
          else
            echo "No .png files to add."
          fi
          if ls **/*.json 1> /dev/null 2>&1; then
            git add **/*.json
            commit=1
          else
            echo "No .json files to add."
          fi
          if [ "$commit" -eq 1 ]; then
            git commit -m "Added generated .png and .json files for changed .obj files"
            git push origin dev/generate-vanilla
          else
            echo "Nothing to commit."
          fi

